# Generated by Django 5.1.1 on 2025-04-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='instagram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_Name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
            ],
        ),
    ]
